version: '3.9'

services:
  web:
    build: ./webProg
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'books'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: ''
    restart: always
